#!/bin/python3

# Project: Bubble Sort
# This: bubblesort.py
# Author: C Robinson
# Date: 07 Sep 2018
# Purpose: Solve Bubble Sort problem. What this problem does:
#                 - Iterates through array multiple times for each element, minus what has already been sorted.
#                 - Swaps elements if the element on left is smaller than element on the right.

import math
import os
import random
import re
import sys

# Complete the countSwaps function below.
def countSwaps(a):
    n = 0
    for i in range(len(a) - 1):
        for j in range(len(a) - 1 - i):
            if a[j] > a[j+1]:
                a[j], a[j + 1] = a[j + 1], a[j]
                n += 1
    print('Array is sorted in ' + str(n) + ' swaps.')
    print('First Element: ' + str(a[0]))
    print('Last Element: ' + str(a[len(a) - 1]))

if __name__ == '__main__':
    n = int(input())
    a = list(map(int, input().rstrip().split()))
    countSwaps(a)
